from KratosMultiphysics import *
from KratosMultiphysics.FluidDynamicsApplication import *
#from KratosMultiphysics.ConvectionDiffusionApplication import *
#from KratosMultiphysics.MeshMovingApplication import *
#from KratosMultiphysics.FSIApplication import *
#from KratosMultiphysics.StructuralMechanicsApplication import *
#from KratosMultiphysics import mpi
#from KratosMultiphysics.MPISearchApplication import *

Tester.SetVerbosity(Tester.Verbosity.TESTS_OUTPUTS)

#Tester.RunTestCases('*GenerateBins3DMPI')
#Tester.RunTestCases('TestSplitTetrahedra')
#Tester.RunTestCases('TestDivideGeometryTetrahedra3D4ComplexDivision')
#Tester.RunTestCases('TestDivideGeometryTetrahedra3D4ComplexDivisionRiccardo')
#Tester.RunTestCases('TestTriangle2D3*')
#Tester.RunTestCases('*Embedded*')
#Tester.RunTestCases('*Navier*')
#Tester.RunTestCases('*Intersected*')
#Tester.RunTestCases('*Distance*')
#Tester.RunTestCases('*DiscontUtils')
#Tester.RunTestCases('*DivideGeometry*')
#Tester.RunTestCases('*ModifiedShapeFunctions*')
#Tester.RunTestCases('*SkinVisualizationProcess*')
#Tester.RunTestCases('TestPlaneApproximationUtility*')
#Tester.RunTestCases('TestIntersectionUtilitiesTriangleLine*')
#Tester.RunTestCases('TestIntersectionUtilitiesLineLine*')
#Tester.RunTestCases('TestIntersectionUtilitiesLineLineThroughPoint')
#Tester.RunTestCases('TestDiscontinuousDistanceProcessPlaneApproximation3D')
#Tester.RunTestCases('*DistanceModificationTriangle')
#Tester.RunTestCases('TestDiscontinuousDistanceProcessOneEdgeIntersections')
#Tester.RunTestCases('TestDiscontinuousDistanceMultipleIntersections')
#Tester.RunTestCases('TestDiscontinuousDistanceProcessSharpCornerInCube')
#Tester.RunTestCases('TestDiscontinuousDistanceSails')
#Tester.RunTestCases('TestDiscontinuousDistance*')
#Tester.RunTestCases('TestIntersectionUtilities*')
#Tester.RunTestCases('TestDiscontinuousDistanceSails')
#Tester.RunTestCases('TestDiscontinuousDistanceProcessHorizontalPlane2D')
#Tester.RunTestCases('TestDiscontinuousDistanceProcessPlaneApproximation2D')
#Tester.RunTestCases('TestDistanceProcessSquareRing2D')
#Tester.RunTestCases('TestIntersectionUtilitiesLineBoxIntersectionNoHitpoint')
#Tester.RunTestCases('TestIntersectionUtilitiesLineBoxIntersectionSingle')
#Tester.RunTestCases('TestIntersectionUtilitiesLineBoxIntersectionDouble')
#Tester.RunTestCases('TestFindIntersectedElementsProcess2D')
#Tester.RunTestCases('TestEmbeddedElementDiscontinuous2D3N')
#Tester.RunTestCases('*Distance*')
#Tester.RunTestCases('TestDistanceProcessDoubleEmbeddedVariable')
#Tester.RunTestCases('TestDiscontinuousDistanceProcessArrayEmbeddedVariableComplex')
#Tester.RunTestCases('TestDiscontinuousDistanceProcessDoubleEmbeddedVariableComplex')
#Tester.RunTestCases('*ConvergenceAccelerator')
#Tester.RunTestCases('TestEmbeddedSkinUtility2D')
#Tester.RunTestCases('TestPartitionedFSIUtilities*')
#Tester.RunTestCases('*DiscontinuousPressureInterpolator*')
#Tester.RunTestCases('TestPartitionedFSIUtilitiesComputeConsistentResidual')
#Tester.RunTestCases('*FixedMeshALE*')
#Tester.RunTestCases('*EmbeddedNodal*')
#Tester.RunTestCases('TestTetrahedraInCubeDistanceProcess')
#Tester.RunTestCases('*DistanceModification*')
#Tester.RunTestCases('TestConstantRelaxationConvergenceAccelerator')
#Tester.RunTestCases('TestRecursiveMVQNConvergenceAccelerator')
#Tester.RunTestCases('TestSmallDisplacementMixedVolumetricStrainElement*')
#Tester.RunTestCases('TestSmallDisplacementMixedVolumetricStrainElement*')
#Tester.RunTestCases('TestSmallDisplacementMixedVolumetricStrainElement2D3NResidual')
#Tester.RunTestCases('TestUserProvidedLinearElasticLaw*')
#Tester.RunTestCases('*ConstitutiveLawUt*')
#Tester.RunTestCases('TestPartitionedFSIUtilitiesArray2DEmbeddedToPositiveFacePressureInterpolator')
#Tester.RunTestCases('TestMembraneElement*')
#Tester.RunTestCases('*KratosFlags*')
#Tester.RunTestCases('*Drag*')
Tester.RunTestCases('*ExplicitBlockBuilderAndSolver*')
Tester.RunTestCases('*ExplicitSolvingStrategy*')
Tester.RunTestCases('*CompressibleNavierStokesExplicit*')
#Tester.RunTestCases('*ShockDetection*')
#Tester.RunTestCases('TestEulerianDiff*')
#Tester.RunTestCases('TestMPICommunicator*')
#Tester.RunTestCases('*ShockCapturing*')

#Tester.RunTestSuite('KratosCoreGeometriesFastSuite')
#Tester.RunTestSuite('KratosCoreFastSuite')
#Tester.RunTestSuite('MeshMovingApplicationFastSuite')
#Tester.RunTestSuite('FSIApplicationFastSuite')
#Tester.RunTestSuite('FluidDynamicsApplicationFastSuite')
#Tester.RunTestSuite('KratosMPICoreFastSuite')

#Tester.RunAllTestCases()
